/// <mls fileReference="_102053_/l2/molecules/skill.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-08-26T17:55:59.110Z.

export const project = '102053';

// Este projeto não tem tema local.
export const theme = null;

export const groups = [
    { name: 'groupEnterBoolean', molecules: 4, indexDefs: '/_102053_/l2/molecules/groupenterboolean/index.defs' },
    { name: 'groupEnterDate', molecules: 4, indexDefs: '/_102053_/l2/molecules/groupenterdate/index.defs' },
    { name: 'groupEnterText', molecules: 8, indexDefs: '/_102053_/l2/molecules/groupentertext/index.defs' },
    { name: 'groupExpandContent', molecules: 5, indexDefs: '/_102053_/l2/molecules/groupexpandcontent/index.defs' },
    { name: 'groupSelectOne', molecules: 12, indexDefs: '/_102053_/l2/molecules/groupselectone/index.defs' },
    { name: 'groupViewChart', molecules: 6, indexDefs: '/_102053_/l2/molecules/groupviewchart/index.defs' },
    { name: 'groupViewTable', molecules: 11, indexDefs: '/_102053_/l2/molecules/groupviewtable/index.defs' },
];

export const skill = `# Molecules — catálogo do projeto mls-102053 (7 grupos)

## Como consumir (em etapas, para não estourar o prompt)

1. Leia ESTE arquivo e escolha os GRUPOS que a página precisa. A lista de moléculas de cada grupo está abaixo para isso: se o nome de uma molécula corresponde ao que a região precisa, o grupo dela é o caminho.
2. Para cada grupo escolhido, leia o catálogo do grupo (index.defs) e escolha a MOLÉCULA pela descrição completa.
3. Antes de escrever marcação, leia o contrato de uso do grupo (o index.defs do grupo aponta para ele).

Se a página precisa de algo que NENHUM grupo abaixo cobre, responda que não há molécula disponível para aquela região — NUNCA invente uma tag.

## Grupos disponíveis

### groupEnterBoolean (4 moléculas)
Allows the user to input a true/false decision. Value is boolean — starts as false until the user changes it. Supports Label and Helper slot tags. Implementations are toggle/switch and checkbox, fully interchangeable by swapping the component tag.
Moléculas: ml-boolean-segmented, ml-checkbox-preference, ml-toggle-icon, ml-toggle-switch

### groupEnterDate (4 moléculas)
Allows the user to input a date only (no time). Ideal for birth dates, due dates, contract effective dates, expiration dates, and any scenario where the time of day is irrelevant. Implementations include date picker, masked date input, inline calendar, and month/year picker.
Moléculas: ml-compact-calendar, ml-date-picker, ml-date-shortcut-picker, ml-inline-calendar

### groupEnterText (8 moléculas)
Allows the user to input free-form text. Ideal for names, descriptions, comments, emails, passwords, and any textual data. Implementations include input, textarea, password input, masked input, input OTP, search input, and tag input.
Moléculas: ml-address-field, ml-cpf-input, ml-enter-text, ml-floating-text-input, ml-multiline-text, ml-password-strength-input, ml-phone-input, ml-tag-input

### groupExpandContent (5 moléculas)
Allows the user to expand or collapse content sections to see more or less details. Manages multiple sections via Section slot tags with title, disabled, and expanded attributes. Supports accordion mode (single open) or multiple open simultaneously. Implementations include accordion, collapsible, show more/show less, expandable row, and details/summary.
Moléculas: ml-accordion, ml-collapsible-panel, ml-readmore-expand, ml-reveal-overlay, ml-single-expand-content

### groupSelectOne (12 moléculas)
Allows the user to select exactly one option from a list of mutually exclusive choices. Ideal for scenarios where a single, clear decision is required. Layout is chosen via the \`variant\` property: dropdown/combobox (default), radio group, segmented control, list picker, and table (a radio group laid out as a table with column headers — for comparing options that each have multiple attributes, e.g. plan name/price/limits). The selected value is always the chosen item value, regardless of variant.
Moléculas: ml-card-selector, ml-combobox, ml-dial-select, ml-discrete-slider, ml-listbox-sidebar-select, ml-radio-group, ml-segmented-control, ml-select, ml-select-dropdown, ml-select-dropdown-img, ml-select-one-autocomplete, ml-table-single-select

### groupViewChart (6 moléculas)
Displays data through graphical representation. Data provided via Series and Point slot tags. All chart implementations share the same data contract — swap the component tag to change visualization. Supports multi-series (Line, Bar, Area, Radar, Scatter) and single-series (Pie, Donut, Funnel). Implementations include bar chart, line chart, area chart, pie chart, donut chart, scatter chart, radar chart, and funnel chart.
Moléculas: ml-area-chart, ml-bar-chart, ml-line-chart, ml-pie-chart, ml-radar-chart, ml-scatter-plot

### groupViewTable (11 moléculas)
Displays structured data in tabular format. Data provided via TableHeader, TableBody, TableRow, TableHead, and TableCell slot tags. Supports column sorting, row selection with checkboxes, pagination, and isEditing propagation to web components inside cells. Implementations include data table, simple table, editable grid, virtualized table, and tree table.
Moléculas: ml-advanced-data-table, ml-data-table, ml-data-table-minimal, ml-grouping-table, ml-inline-edit-table, ml-lazy-record-detail-table, ml-lcrud-detail-grid, ml-pivot-table, ml-responsive-data-table, ml-responsive-table, ml-view-table

Este projeto não tem tema local.
`;
