/// <mls fileReference="_102053_/l2/molecules/groupenterdate/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-08-26T17:55:58.856Z.

export const group = 'groupEnterDate';

// Contrato do grupo (slots, propriedades, eventos, exemplos) — referenciado, nunca
// copiado (contrato é manual: decisão de 17/08). Leia ANTES de escrever marcação.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupEnterDate/usage';

// Lista estruturada, para consumo determinístico (gates, lints).
// layout = eixos do layoutConfig que VARIAM entre os irmãos deste grupo.
export const molecules = [
    { tag: 'groupenterdate--ml-compact-calendar', layout: { dateInput: 'inline-calendar' }, defs: '/_102053_/l2/molecules/groupenterdate/ml-compact-calendar.defs' },
    { tag: 'groupenterdate--ml-date-picker', layout: { dateInput: 'calendar-popover' }, defs: '/_102053_/l2/molecules/groupenterdate/ml-date-picker.defs' },
    { tag: 'groupenterdate--ml-date-shortcut-picker', layout: { dateInput: 'shortcuts' }, defs: '/_102053_/l2/molecules/groupenterdate/ml-date-shortcut-picker.defs' },
    { tag: 'groupenterdate--ml-inline-calendar', layout: { dateInput: 'inline-calendar' }, defs: '/_102053_/l2/molecules/groupenterdate/ml-inline-calendar.defs' },
];

// Tabela "Quick reference" (cenário -> recomendadas). Editorial: não é derivada do catálogo.
export const scenarios = [
    { scenario: 'You need a compact calendar in a constrained layout', recommended: ['groupenterdate--ml-compact-calendar'] },
    { scenario: 'Users should type a date with optional calendar assistance', recommended: ['groupenterdate--ml-date-picker'] },
    { scenario: 'Common relative dates should be available as shortcuts', recommended: ['groupenterdate--ml-date-shortcut-picker'] },
    { scenario: 'The calendar should remain visible while users browse dates', recommended: ['groupenterdate--ml-inline-calendar'] },
    { scenario: 'The value must be stored as an ISO date with no time', recommended: ['groupenterdate--ml-compact-calendar', 'groupenterdate--ml-date-picker', 'groupenterdate--ml-date-shortcut-picker', 'groupenterdate--ml-inline-calendar'] },
];

export const skill = `# groupEnterDate — moléculas disponíveis (mls-102053)

Objetivo do grupo: Allows the user to input a date only (no time). Ideal for birth dates, due dates, contract effective dates, expiration dates, and any scenario where the time of day is irrelevant. Implementations include date picker, masked date input, inline calendar, and month/year picker.

## Como escolher

1. Se o cenário da página bate com um da tabela abaixo, comece pelas recomendadas.
2. Desempate pelo layout e pela descrição completa de cada molécula.
3. Antes de escrever a marcação, leia o contrato de uso do grupo (usageContract).
   A tag deve ser copiada EXATAMENTE como está aqui.

## Cenários (quick reference)

| cenário | recomendadas |
|---|---|
| You need a compact calendar in a constrained layout | ml-compact-calendar |
| Users should type a date with optional calendar assistance | ml-date-picker |
| Common relative dates should be available as shortcuts | ml-date-shortcut-picker |
| The calendar should remain visible while users browse dates | ml-inline-calendar |
| The value must be stored as an ISO date with no time | ml-compact-calendar, ml-date-picker, ml-date-shortcut-picker, ml-inline-calendar |

## Moléculas (4)

- **groupenterdate--ml-compact-calendar** · dateInput: inline-calendar — Allow the user to select a single date from an always-visible inline calendar grid. The calendar renders directly inside the page layout without a popover, shows the current month with navigation controls, highlights today and the selected date, optionally displays week numbers, and respects min/max date bounds. It also has a view-only mode that shows the selected value as plain text.
- **groupenterdate--ml-date-picker** · dateInput: calendar-popover — Allow the user to choose a single date by clicking a trigger button that opens a calendar dropdown. The selected date is displayed on the trigger in a locale-aware format, and a clear action inside the panel resets the selection. The component supports disabled, readonly, required, loading, and error states, and has a view-only mode that shows the value as static text.
- **groupenterdate--ml-date-shortcut-picker** · dateInput: shortcuts — Provide a date selection interface that offers configurable shortcut options for common dates alongside a manual date entry field. It allows users to quickly select predefined dates or enter a date manually, maintaining compliance with the groupEnterDate contract.
- **groupenterdate--ml-inline-calendar** · dateInput: inline-calendar — An inline calendar molecule for selecting a single date, always visible during editing, with monthly navigation. It follows the groupEnterDate contract for data entry and display states.
`;
